CREATE TABLE film (
       id int primary key,
       category_id int,
       title varchar(120),
       year_production int,
       plot varchar(2048),
       cost double precision
);

CREATE TABLE category (
        id int primary key,
        category_name varchar(64)
);

CREATE TABLE bucket (
       id int GENERATED BY DEFAULT AS IDENTITY primary key ,
       film_id int,
       date_time timestamp,
       qty int
);


ALTER TABLE PUBLIC.bucket
    ADD FOREIGN KEY (film_id)
        REFERENCES PUBLIC.film(id);


ALTER TABLE PUBLIC.film
    ADD FOREIGN KEY (category_id)
        REFERENCES PUBLIC.category(id);

